### ISSUE TITLE
Externalize geoid url variable

### ISSUE THREAD

**Issue by matt-bo-29** [ACCESS-Cloud-Based-InSAR/dem-stitcher#100]
Hello!

Can we consider to externalize the hardcoded parameter 'ARIA_GEOIDS' ?
It will be helpfull in order to change the url without code modification (if the link does not respond for example). We could imaging to place a link to local geoid files for example.

```python
import os 
ARIA_GEOIDS = os.environ.get('ARIA_GEOIDS', 'https://aria-geoid.s3.us-west-2.amazonaws.com')
GEOID_PATHS_AGI = {
    'geoid_18': f'{DATA_PATH}/geoid_18.tif',
    'egm_08': f'{ARIA_GEOIDS}/egm08_25.tif',
    'egm_96': f'{DATA_PATH}/egm96_15.gtx',
}
```

**Comment by cmarshak** [comment]
I think this is a good idea - we could add a keyword argument to the main stitcher routine.
